const bgByType = {
    normal: "bg-gradient-to-t from-slate-300 to-slate-500",
    fighting: "bg-gradient-to-t from-yellow-700 to-yellow-900",
    flying: "bg-gradient-to-t from-cyan-400 to-cyan-600",
    poison: "bg-gradient-to-t from-purple-700 to-purple-900",
    ground: "bg-gradient-to-t from-neutral-400 to-neutral-600",
    rock: "bg-gradient-to-t from-stone-700 to-stone-900",
    bug: "bg-gradient-to-t from-rose-700 to-rose-900",
    ghost: "bg-gradient-to-t from-gray-400 to-gray-600",
    steel: "bg-gradient-to-t from-teal-400 to-teal-600",
    fire: "bg-gradient-to-t from-orange-300 to-orange-500",
    water: "bg-gradient-to-t from-blue-300 to-blue-500",
    grass: "bg-gradient-to-t from-green-300 to-green-500",
    electric: "bg-gradient-to-t from-yellow-300 to-yellow-500",
    psychic: "bg-gradient-to-t from-lime-400 to-lime-600",
    ice: "bg-gradient-to-t from-sky-700 to-sky-900",
    dragon: "bg-gradient-to-t from-red-400 to-red-600",
    dark: "bg-gradient-to-t from-neutral-700 to-neutral-900",
    fairy: "bg-gradient-to-t from-cyan-400 to-cyan-600",
    unknown: "",
    shadow: "",
  };

  const borderByType = {
    normal: "border-slate-500",
    fighting: "border-yellow-900",
    flying: "border-cyan-600",
    poison: "border-purple-900",
    ground: "border-neutral-600",
    rock: "border-stone-900",
    bug: "border-rose-900",
    ghost: "border-gray-600",
    steel: "border-teal-600",
    fire: "border-orange-500",
    water: "border-blue-500",
    grass: "border-green-500",
    electric: "border-yellow-500",
    psychic: "border-lime-600",
    ice: "border-sky-900",
    dragon: "border-red-600",
    dark: "border-neutral-900",
    fairy: "border-cyan-600",
    unknown: "",
    shadow: "",
  };
   
  export { bgByType, borderByType};